// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: eiyarowalletd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressType int32

const (
	AddressType_ADDRESS_TYPE_UNSPECIFIED AddressType = 0
	AddressType_ADDRESS_TYPE_P2PKH       AddressType = 1
	AddressType_ADDRESS_TYPE_P2PK        AddressType = 2
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "ADDRESS_TYPE_UNSPECIFIED",
		1: "ADDRESS_TYPE_P2PKH",
		2: "ADDRESS_TYPE_P2PK",
	}
	AddressType_value = map[string]int32{
		"ADDRESS_TYPE_UNSPECIFIED": 0,
		"ADDRESS_TYPE_P2PKH":       1,
		"ADDRESS_TYPE_P2PK":        2,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_eiyarowalletd_proto_enumTypes[0].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_eiyarowalletd_proto_enumTypes[0]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{0}
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{0}
}

type GetBalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Available       uint64                 `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Pending         uint64                 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	AddressBalances []*AddressBalances     `protobuf:"bytes,3,rep,name=addressBalances,proto3" json:"addressBalances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetBalanceResponse) GetAddressBalances() []*AddressBalances {
	if x != nil {
		return x.AddressBalances
	}
	return nil
}

type AddressBalances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Available     uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Pending       uint64                 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBalances) Reset() {
	*x = AddressBalances{}
	mi := &file_eiyarowalletd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBalances) ProtoMessage() {}

func (x *AddressBalances) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBalances.ProtoReflect.Descriptor instead.
func (*AddressBalances) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBalances) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressBalances) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *AddressBalances) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type CreateUnsignedTransactionsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	From                     []string               `protobuf:"bytes,3,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,4,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,5,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	Payload                  []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Limit                    *string                `protobuf:"bytes,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsRequest) Reset() {
	*x = CreateUnsignedTransactionsRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsRequest) ProtoMessage() {}

func (x *CreateUnsignedTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsRequest.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUnsignedTransactionsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUnsignedTransactionsRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateUnsignedTransactionsRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CreateUnsignedTransactionsRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *CreateUnsignedTransactionsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateUnsignedTransactionsRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type CreateUnsignedTransactionsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUnsignedTransactionsResponse) Reset() {
	*x = CreateUnsignedTransactionsResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedTransactionsResponse) ProtoMessage() {}

func (x *CreateUnsignedTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedTransactionsResponse.ProtoReflect.Descriptor instead.
func (*CreateUnsignedTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUnsignedTransactionsResponse) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

type CreateUnsignedCompoundTransactionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	From                     []string               `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,3,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	Limit                    *string                `protobuf:"bytes,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateUnsignedCompoundTransactionRequest) Reset() {
	*x = CreateUnsignedCompoundTransactionRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedCompoundTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedCompoundTransactionRequest) ProtoMessage() {}

func (x *CreateUnsignedCompoundTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedCompoundTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateUnsignedCompoundTransactionRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUnsignedCompoundTransactionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateUnsignedCompoundTransactionRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CreateUnsignedCompoundTransactionRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *CreateUnsignedCompoundTransactionRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type CreateUnsignedCompoundTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateUnsignedCompoundTransactionResponse) Reset() {
	*x = CreateUnsignedCompoundTransactionResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnsignedCompoundTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnsignedCompoundTransactionResponse) ProtoMessage() {}

func (x *CreateUnsignedCompoundTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnsignedCompoundTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateUnsignedCompoundTransactionResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUnsignedCompoundTransactionResponse) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

type ShowAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressType   AddressType            `protobuf:"varint,1,opt,name=addressType,proto3,enum=eiyarowalletd.AddressType" json:"addressType,omitempty"`
	IncludeBoth   bool                   `protobuf:"varint,2,opt,name=includeBoth,proto3" json:"includeBoth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesRequest) Reset() {
	*x = ShowAddressesRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesRequest) ProtoMessage() {}

func (x *ShowAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesRequest.ProtoReflect.Descriptor instead.
func (*ShowAddressesRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{7}
}

func (x *ShowAddressesRequest) GetAddressType() AddressType {
	if x != nil {
		return x.AddressType
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

func (x *ShowAddressesRequest) GetIncludeBoth() bool {
	if x != nil {
		return x.IncludeBoth
	}
	return false
}

type ShowAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowAddressesResponse) Reset() {
	*x = ShowAddressesResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAddressesResponse) ProtoMessage() {}

func (x *ShowAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAddressesResponse.ProtoReflect.Descriptor instead.
func (*ShowAddressesResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{8}
}

func (x *ShowAddressesResponse) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

type NewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressType   AddressType            `protobuf:"varint,1,opt,name=addressType,proto3,enum=eiyarowalletd.AddressType" json:"addressType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{9}
}

func (x *NewAddressRequest) GetAddressType() AddressType {
	if x != nil {
		return x.AddressType
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

type NewAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is the primary address string returned by the daemon.
	// When addressType is unspecified it defaults to P2PK.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// p2pkAddress and p2pkhAddress are returned for single-sig wallets.
	// For multisig wallets (P2SH), these fields are empty.
	P2PkAddress   string `protobuf:"bytes,2,opt,name=p2pkAddress,proto3" json:"p2pkAddress,omitempty"`
	P2PkhAddress  string `protobuf:"bytes,3,opt,name=p2pkhAddress,proto3" json:"p2pkhAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressResponse) Reset() {
	*x = NewAddressResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressResponse) ProtoMessage() {}

func (x *NewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressResponse.ProtoReflect.Descriptor instead.
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{10}
}

func (x *NewAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NewAddressResponse) GetP2PkAddress() string {
	if x != nil {
		return x.P2PkAddress
	}
	return ""
}

func (x *NewAddressResponse) GetP2PkhAddress() string {
	if x != nil {
		return x.P2PkhAddress
	}
	return ""
}

type BroadcastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsDomain       bool                   `protobuf:"varint,1,opt,name=isDomain,proto3" json:"isDomain,omitempty"`
	Transactions   [][]byte               `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	AllowOrphan    bool                   `protobuf:"varint,3,opt,name=allowOrphan,proto3" json:"allowOrphan,omitempty"`
	IsHighPriority *bool                  `protobuf:"varint,4,opt,name=isHighPriority,proto3,oneof" json:"isHighPriority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastRequest) GetIsDomain() bool {
	if x != nil {
		return x.IsDomain
	}
	return false
}

func (x *BroadcastRequest) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BroadcastRequest) GetAllowOrphan() bool {
	if x != nil {
		return x.AllowOrphan
	}
	return false
}

func (x *BroadcastRequest) GetIsHighPriority() bool {
	if x != nil && x.IsHighPriority != nil {
		return *x.IsHighPriority
	}
	return false
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIDs         []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{13}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{14}
}

type Outpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outpoint) Reset() {
	*x = Outpoint{}
	mi := &file_eiyarowalletd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outpoint) ProtoMessage() {}

func (x *Outpoint) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outpoint.ProtoReflect.Descriptor instead.
func (*Outpoint) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{15}
}

func (x *Outpoint) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Outpoint) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type UtxosByAddressesEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Outpoint      *Outpoint              `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	UtxoEntry     *UtxoEntry             `protobuf:"bytes,3,opt,name=utxoEntry,proto3" json:"utxoEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxosByAddressesEntry) Reset() {
	*x = UtxosByAddressesEntry{}
	mi := &file_eiyarowalletd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxosByAddressesEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxosByAddressesEntry) ProtoMessage() {}

func (x *UtxosByAddressesEntry) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxosByAddressesEntry.ProtoReflect.Descriptor instead.
func (*UtxosByAddressesEntry) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{16}
}

func (x *UtxosByAddressesEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UtxosByAddressesEntry) GetOutpoint() *Outpoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *UtxosByAddressesEntry) GetUtxoEntry() *UtxoEntry {
	if x != nil {
		return x.UtxoEntry
	}
	return nil
}

type ScriptPublicKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ScriptPublicKey string                 `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScriptPublicKey) Reset() {
	*x = ScriptPublicKey{}
	mi := &file_eiyarowalletd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptPublicKey) ProtoMessage() {}

func (x *ScriptPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptPublicKey.ProtoReflect.Descriptor instead.
func (*ScriptPublicKey) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{17}
}

func (x *ScriptPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ScriptPublicKey) GetScriptPublicKey() string {
	if x != nil {
		return x.ScriptPublicKey
	}
	return ""
}

type UtxoEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ScriptPublicKey *ScriptPublicKey       `protobuf:"bytes,2,opt,name=scriptPublicKey,proto3" json:"scriptPublicKey,omitempty"`
	BlockDaaScore   uint64                 `protobuf:"varint,3,opt,name=blockDaaScore,proto3" json:"blockDaaScore,omitempty"`
	IsCoinbase      bool                   `protobuf:"varint,4,opt,name=isCoinbase,proto3" json:"isCoinbase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UtxoEntry) Reset() {
	*x = UtxoEntry{}
	mi := &file_eiyarowalletd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEntry) ProtoMessage() {}

func (x *UtxoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEntry.ProtoReflect.Descriptor instead.
func (*UtxoEntry) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{18}
}

func (x *UtxoEntry) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UtxoEntry) GetScriptPublicKey() *ScriptPublicKey {
	if x != nil {
		return x.ScriptPublicKey
	}
	return nil
}

func (x *UtxoEntry) GetBlockDaaScore() uint64 {
	if x != nil {
		return x.BlockDaaScore
	}
	return 0
}

func (x *UtxoEntry) GetIsCoinbase() bool {
	if x != nil {
		return x.IsCoinbase
	}
	return false
}

type GetExternalSpendableUTXOsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsRequest) Reset() {
	*x = GetExternalSpendableUTXOsRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsRequest) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsRequest.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{19}
}

func (x *GetExternalSpendableUTXOsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetExternalSpendableUTXOsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entries       []*UtxosByAddressesEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalSpendableUTXOsResponse) Reset() {
	*x = GetExternalSpendableUTXOsResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalSpendableUTXOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalSpendableUTXOsResponse) ProtoMessage() {}

func (x *GetExternalSpendableUTXOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalSpendableUTXOsResponse.ProtoReflect.Descriptor instead.
func (*GetExternalSpendableUTXOsResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{20}
}

func (x *GetExternalSpendableUTXOsResponse) GetEntries() []*UtxosByAddressesEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Since SendRequest contains a password - this command should only be used on a trusted or secure connection
type SendRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ToAddress                string                 `protobuf:"bytes,1,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
	Amount                   uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Password                 string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	From                     []string               `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	UseExistingChangeAddress bool                   `protobuf:"varint,5,opt,name=useExistingChangeAddress,proto3" json:"useExistingChangeAddress,omitempty"`
	IsSendAll                bool                   `protobuf:"varint,6,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`
	Limit                    *string                `protobuf:"bytes,7,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{21}
}

func (x *SendRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendRequest) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendRequest) GetUseExistingChangeAddress() bool {
	if x != nil {
		return x.UseExistingChangeAddress
	}
	return false
}

func (x *SendRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *SendRequest) GetLimit() string {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return ""
}

type SendResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TxIDs              []string               `protobuf:"bytes,1,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	SignedTransactions [][]byte               `protobuf:"bytes,2,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{22}
}

func (x *SendResponse) GetTxIDs() []string {
	if x != nil {
		return x.TxIDs
	}
	return nil
}

func (x *SendResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

// Since SignRequest contains a password - this command should only be used on a trusted or secure connection
type SignRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UnsignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=unsignedTransactions,proto3" json:"unsignedTransactions,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{23}
}

func (x *SignRequest) GetUnsignedTransactions() [][]byte {
	if x != nil {
		return x.UnsignedTransactions
	}
	return nil
}

func (x *SignRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SignedTransactions [][]byte               `protobuf:"bytes,1,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{24}
}

func (x *SignResponse) GetSignedTransactions() [][]byte {
	if x != nil {
		return x.SignedTransactions
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_eiyarowalletd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{25}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_eiyarowalletd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eiyarowalletd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_eiyarowalletd_proto_rawDescGZIP(), []int{26}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_eiyarowalletd_proto protoreflect.FileDescriptor

const file_eiyarowalletd_proto_rawDesc = "" +
	"\n" +
	"\x13eiyarowalletd.proto\x12\reiyarowalletd\"\x13\n" +
	"\x11GetBalanceRequest\"\x96\x01\n" +
	"\x12GetBalanceResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x02 \x01(\x04R\apending\x12H\n" +
	"\x0faddressBalances\x18\x03 \x03(\v2\x1e.eiyarowalletd.AddressBalancesR\x0faddressBalances\"c\n" +
	"\x0fAddressBalances\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x18\n" +
	"\apending\x18\x03 \x01(\x04R\apending\"\x82\x02\n" +
	"!CreateUnsignedTransactionsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04from\x18\x03 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x04 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x05 \x01(\bR\tisSendAll\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x19\n" +
	"\x05limit\x18\a \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"X\n" +
	"\"CreateUnsignedTransactionsResponse\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\"\xb9\x01\n" +
	"(CreateUnsignedCompoundTransactionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04from\x18\x02 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x03 \x01(\bR\x18useExistingChangeAddress\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"_\n" +
	")CreateUnsignedCompoundTransactionResponse\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\"v\n" +
	"\x14ShowAddressesRequest\x12<\n" +
	"\vaddressType\x18\x01 \x01(\x0e2\x1a.eiyarowalletd.AddressTypeR\vaddressType\x12 \n" +
	"\vincludeBoth\x18\x02 \x01(\bR\vincludeBoth\"1\n" +
	"\x15ShowAddressesResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\"Q\n" +
	"\x11NewAddressRequest\x12<\n" +
	"\vaddressType\x18\x01 \x01(\x0e2\x1a.eiyarowalletd.AddressTypeR\vaddressType\"t\n" +
	"\x12NewAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12 \n" +
	"\vp2pkAddress\x18\x02 \x01(\tR\vp2pkAddress\x12\"\n" +
	"\fp2pkhAddress\x18\x03 \x01(\tR\fp2pkhAddress\"\xb4\x01\n" +
	"\x10BroadcastRequest\x12\x1a\n" +
	"\bisDomain\x18\x01 \x01(\bR\bisDomain\x12\"\n" +
	"\ftransactions\x18\x02 \x03(\fR\ftransactions\x12 \n" +
	"\vallowOrphan\x18\x03 \x01(\bR\vallowOrphan\x12+\n" +
	"\x0eisHighPriority\x18\x04 \x01(\bH\x00R\x0eisHighPriority\x88\x01\x01B\x11\n" +
	"\x0f_isHighPriority\")\n" +
	"\x11BroadcastResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"F\n" +
	"\bOutpoint\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\x9e\x01\n" +
	"\x15UtxosByAddressesEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x123\n" +
	"\boutpoint\x18\x02 \x01(\v2\x17.eiyarowalletd.OutpointR\boutpoint\x126\n" +
	"\tutxoEntry\x18\x03 \x01(\v2\x18.eiyarowalletd.UtxoEntryR\tutxoEntry\"U\n" +
	"\x0fScriptPublicKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12(\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\tR\x0fscriptPublicKey\"\xb3\x01\n" +
	"\tUtxoEntry\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12H\n" +
	"\x0fscriptPublicKey\x18\x02 \x01(\v2\x1e.eiyarowalletd.ScriptPublicKeyR\x0fscriptPublicKey\x12$\n" +
	"\rblockDaaScore\x18\x03 \x01(\x04R\rblockDaaScore\x12\x1e\n" +
	"\n" +
	"isCoinbase\x18\x04 \x01(\bR\n" +
	"isCoinbase\"<\n" +
	" GetExternalSpendableUTXOsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"c\n" +
	"!GetExternalSpendableUTXOsResponse\x12>\n" +
	"\aEntries\x18\x01 \x03(\v2$.eiyarowalletd.UtxosByAddressesEntryR\aEntries\"\xf2\x01\n" +
	"\vSendRequest\x12\x1c\n" +
	"\ttoAddress\x18\x01 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x04 \x03(\tR\x04from\x12:\n" +
	"\x18useExistingChangeAddress\x18\x05 \x01(\bR\x18useExistingChangeAddress\x12\x1c\n" +
	"\tisSendAll\x18\x06 \x01(\bR\tisSendAll\x12\x19\n" +
	"\x05limit\x18\a \x01(\tH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"T\n" +
	"\fSendResponse\x12\x14\n" +
	"\x05txIDs\x18\x01 \x03(\tR\x05txIDs\x12.\n" +
	"\x12signedTransactions\x18\x02 \x03(\fR\x12signedTransactions\"]\n" +
	"\vSignRequest\x122\n" +
	"\x14unsignedTransactions\x18\x01 \x03(\fR\x14unsignedTransactions\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\fSignResponse\x12.\n" +
	"\x12signedTransactions\x18\x01 \x03(\fR\x12signedTransactions\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion*Z\n" +
	"\vAddressType\x12\x1c\n" +
	"\x18ADDRESS_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ADDRESS_TYPE_P2PKH\x10\x01\x12\x15\n" +
	"\x11ADDRESS_TYPE_P2PK\x10\x022\xb7\b\n" +
	"\reiyarowalletd\x12S\n" +
	"\n" +
	"GetBalance\x12 .eiyarowalletd.GetBalanceRequest\x1a!.eiyarowalletd.GetBalanceResponse\"\x00\x12\x80\x01\n" +
	"\x19GetExternalSpendableUTXOs\x12/.eiyarowalletd.GetExternalSpendableUTXOsRequest\x1a0.eiyarowalletd.GetExternalSpendableUTXOsResponse\"\x00\x12\x83\x01\n" +
	"\x1aCreateUnsignedTransactions\x120.eiyarowalletd.CreateUnsignedTransactionsRequest\x1a1.eiyarowalletd.CreateUnsignedTransactionsResponse\"\x00\x12\\\n" +
	"\rShowAddresses\x12#.eiyarowalletd.ShowAddressesRequest\x1a$.eiyarowalletd.ShowAddressesResponse\"\x00\x12S\n" +
	"\n" +
	"NewAddress\x12 .eiyarowalletd.NewAddressRequest\x1a!.eiyarowalletd.NewAddressResponse\"\x00\x12M\n" +
	"\bShutdown\x12\x1e.eiyarowalletd.ShutdownRequest\x1a\x1f.eiyarowalletd.ShutdownResponse\"\x00\x12P\n" +
	"\tBroadcast\x12\x1f.eiyarowalletd.BroadcastRequest\x1a .eiyarowalletd.BroadcastResponse\"\x00\x12A\n" +
	"\x04Send\x12\x1a.eiyarowalletd.SendRequest\x1a\x1b.eiyarowalletd.SendResponse\"\x00\x12A\n" +
	"\x04Sign\x12\x1a.eiyarowalletd.SignRequest\x1a\x1b.eiyarowalletd.SignResponse\"\x00\x12S\n" +
	"\n" +
	"GetVersion\x12 .eiyarowalletd.GetVersionRequest\x1a!.eiyarowalletd.GetVersionResponse\"\x00\x12\x98\x01\n" +
	"!CreateUnsignedCompoundTransaction\x127.eiyarowalletd.CreateUnsignedCompoundTransactionRequest\x1a8.eiyarowalletd.CreateUnsignedCompoundTransactionResponse\"\x00B5Z3github.com/Eiyaro/Eiyaro/cmd/eiyarowallet/daemon/pbb\x06proto3"

var (
	file_eiyarowalletd_proto_rawDescOnce sync.Once
	file_eiyarowalletd_proto_rawDescData []byte
)

func file_eiyarowalletd_proto_rawDescGZIP() []byte {
	file_eiyarowalletd_proto_rawDescOnce.Do(func() {
		file_eiyarowalletd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eiyarowalletd_proto_rawDesc), len(file_eiyarowalletd_proto_rawDesc)))
	})
	return file_eiyarowalletd_proto_rawDescData
}

var file_eiyarowalletd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eiyarowalletd_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_eiyarowalletd_proto_goTypes = []any{
	(AddressType)(0),                                  // 0: eiyarowalletd.AddressType
	(*GetBalanceRequest)(nil),                         // 1: eiyarowalletd.GetBalanceRequest
	(*GetBalanceResponse)(nil),                        // 2: eiyarowalletd.GetBalanceResponse
	(*AddressBalances)(nil),                           // 3: eiyarowalletd.AddressBalances
	(*CreateUnsignedTransactionsRequest)(nil),         // 4: eiyarowalletd.CreateUnsignedTransactionsRequest
	(*CreateUnsignedTransactionsResponse)(nil),        // 5: eiyarowalletd.CreateUnsignedTransactionsResponse
	(*CreateUnsignedCompoundTransactionRequest)(nil),  // 6: eiyarowalletd.CreateUnsignedCompoundTransactionRequest
	(*CreateUnsignedCompoundTransactionResponse)(nil), // 7: eiyarowalletd.CreateUnsignedCompoundTransactionResponse
	(*ShowAddressesRequest)(nil),                      // 8: eiyarowalletd.ShowAddressesRequest
	(*ShowAddressesResponse)(nil),                     // 9: eiyarowalletd.ShowAddressesResponse
	(*NewAddressRequest)(nil),                         // 10: eiyarowalletd.NewAddressRequest
	(*NewAddressResponse)(nil),                        // 11: eiyarowalletd.NewAddressResponse
	(*BroadcastRequest)(nil),                          // 12: eiyarowalletd.BroadcastRequest
	(*BroadcastResponse)(nil),                         // 13: eiyarowalletd.BroadcastResponse
	(*ShutdownRequest)(nil),                           // 14: eiyarowalletd.ShutdownRequest
	(*ShutdownResponse)(nil),                          // 15: eiyarowalletd.ShutdownResponse
	(*Outpoint)(nil),                                  // 16: eiyarowalletd.Outpoint
	(*UtxosByAddressesEntry)(nil),                     // 17: eiyarowalletd.UtxosByAddressesEntry
	(*ScriptPublicKey)(nil),                           // 18: eiyarowalletd.ScriptPublicKey
	(*UtxoEntry)(nil),                                 // 19: eiyarowalletd.UtxoEntry
	(*GetExternalSpendableUTXOsRequest)(nil),          // 20: eiyarowalletd.GetExternalSpendableUTXOsRequest
	(*GetExternalSpendableUTXOsResponse)(nil),         // 21: eiyarowalletd.GetExternalSpendableUTXOsResponse
	(*SendRequest)(nil),                               // 22: eiyarowalletd.SendRequest
	(*SendResponse)(nil),                              // 23: eiyarowalletd.SendResponse
	(*SignRequest)(nil),                               // 24: eiyarowalletd.SignRequest
	(*SignResponse)(nil),                              // 25: eiyarowalletd.SignResponse
	(*GetVersionRequest)(nil),                         // 26: eiyarowalletd.GetVersionRequest
	(*GetVersionResponse)(nil),                        // 27: eiyarowalletd.GetVersionResponse
}
var file_eiyarowalletd_proto_depIdxs = []int32{
	3,  // 0: eiyarowalletd.GetBalanceResponse.addressBalances:type_name -> eiyarowalletd.AddressBalances
	0,  // 1: eiyarowalletd.ShowAddressesRequest.addressType:type_name -> eiyarowalletd.AddressType
	0,  // 2: eiyarowalletd.NewAddressRequest.addressType:type_name -> eiyarowalletd.AddressType
	16, // 3: eiyarowalletd.UtxosByAddressesEntry.outpoint:type_name -> eiyarowalletd.Outpoint
	19, // 4: eiyarowalletd.UtxosByAddressesEntry.utxoEntry:type_name -> eiyarowalletd.UtxoEntry
	18, // 5: eiyarowalletd.UtxoEntry.scriptPublicKey:type_name -> eiyarowalletd.ScriptPublicKey
	17, // 6: eiyarowalletd.GetExternalSpendableUTXOsResponse.Entries:type_name -> eiyarowalletd.UtxosByAddressesEntry
	1,  // 7: eiyarowalletd.eiyarowalletd.GetBalance:input_type -> eiyarowalletd.GetBalanceRequest
	20, // 8: eiyarowalletd.eiyarowalletd.GetExternalSpendableUTXOs:input_type -> eiyarowalletd.GetExternalSpendableUTXOsRequest
	4,  // 9: eiyarowalletd.eiyarowalletd.CreateUnsignedTransactions:input_type -> eiyarowalletd.CreateUnsignedTransactionsRequest
	8,  // 10: eiyarowalletd.eiyarowalletd.ShowAddresses:input_type -> eiyarowalletd.ShowAddressesRequest
	10, // 11: eiyarowalletd.eiyarowalletd.NewAddress:input_type -> eiyarowalletd.NewAddressRequest
	14, // 12: eiyarowalletd.eiyarowalletd.Shutdown:input_type -> eiyarowalletd.ShutdownRequest
	12, // 13: eiyarowalletd.eiyarowalletd.Broadcast:input_type -> eiyarowalletd.BroadcastRequest
	22, // 14: eiyarowalletd.eiyarowalletd.Send:input_type -> eiyarowalletd.SendRequest
	24, // 15: eiyarowalletd.eiyarowalletd.Sign:input_type -> eiyarowalletd.SignRequest
	26, // 16: eiyarowalletd.eiyarowalletd.GetVersion:input_type -> eiyarowalletd.GetVersionRequest
	6,  // 17: eiyarowalletd.eiyarowalletd.CreateUnsignedCompoundTransaction:input_type -> eiyarowalletd.CreateUnsignedCompoundTransactionRequest
	2,  // 18: eiyarowalletd.eiyarowalletd.GetBalance:output_type -> eiyarowalletd.GetBalanceResponse
	21, // 19: eiyarowalletd.eiyarowalletd.GetExternalSpendableUTXOs:output_type -> eiyarowalletd.GetExternalSpendableUTXOsResponse
	5,  // 20: eiyarowalletd.eiyarowalletd.CreateUnsignedTransactions:output_type -> eiyarowalletd.CreateUnsignedTransactionsResponse
	9,  // 21: eiyarowalletd.eiyarowalletd.ShowAddresses:output_type -> eiyarowalletd.ShowAddressesResponse
	11, // 22: eiyarowalletd.eiyarowalletd.NewAddress:output_type -> eiyarowalletd.NewAddressResponse
	15, // 23: eiyarowalletd.eiyarowalletd.Shutdown:output_type -> eiyarowalletd.ShutdownResponse
	13, // 24: eiyarowalletd.eiyarowalletd.Broadcast:output_type -> eiyarowalletd.BroadcastResponse
	23, // 25: eiyarowalletd.eiyarowalletd.Send:output_type -> eiyarowalletd.SendResponse
	25, // 26: eiyarowalletd.eiyarowalletd.Sign:output_type -> eiyarowalletd.SignResponse
	27, // 27: eiyarowalletd.eiyarowalletd.GetVersion:output_type -> eiyarowalletd.GetVersionResponse
	7,  // 28: eiyarowalletd.eiyarowalletd.CreateUnsignedCompoundTransaction:output_type -> eiyarowalletd.CreateUnsignedCompoundTransactionResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_eiyarowalletd_proto_init() }
func file_eiyarowalletd_proto_init() {
	if File_eiyarowalletd_proto != nil {
		return
	}
	file_eiyarowalletd_proto_msgTypes[3].OneofWrappers = []any{}
	file_eiyarowalletd_proto_msgTypes[5].OneofWrappers = []any{}
	file_eiyarowalletd_proto_msgTypes[11].OneofWrappers = []any{}
	file_eiyarowalletd_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eiyarowalletd_proto_rawDesc), len(file_eiyarowalletd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eiyarowalletd_proto_goTypes,
		DependencyIndexes: file_eiyarowalletd_proto_depIdxs,
		EnumInfos:         file_eiyarowalletd_proto_enumTypes,
		MessageInfos:      file_eiyarowalletd_proto_msgTypes,
	}.Build()
	File_eiyarowalletd_proto = out.File
	file_eiyarowalletd_proto_goTypes = nil
	file_eiyarowalletd_proto_depIdxs = nil
}
